version: '3.1'

services:
  exchangetg-bot:
    depends_on:
      - exchangetg-bot-db
    build:
      context: .
    restart: always
  exchangetg-bot-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: telegram_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    expose:
      - 5432