DROP TABLE IF EXISTS currency;

CREATE TABLE currency
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code            VARCHAR(255) UNIQUE,
    value           DOUBLE PRECISION,
    last_updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_currency PRIMARY KEY (id)
);