DROP TABLE IF EXISTS currency;
DROP TABLE IF EXISTS telegram_users;
DROP TABLE IF EXISTS message;

CREATE TABLE currency
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code            VARCHAR(255) UNIQUE,
    value           DOUBLE PRECISION,
    last_updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_currency PRIMARY KEY (id)
);

CREATE TABLE telegram_users
(
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_id VARCHAR(255) UNIQUE ,
    CONSTRAINT pk_telegram_users PRIMARY KEY (user_id)
);
CREATE TABLE message
(
    message_id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text_message_content VARCHAR(255),
    recived_time         TIMESTAMP WITHOUT TIME ZONE,
    user_id              INTEGER,
    CONSTRAINT pk_message PRIMARY KEY (message_id)
);

ALTER TABLE message
    ADD CONSTRAINT FK_MESSAGE_ON_USER FOREIGN KEY (user_id) REFERENCES telegram_users (user_id) ON DELETE CASCADE;